### ISSUE TITLE
Running Design Question List

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/key-mgmt-spec#13]
This is a placeholder epic to track design issues that need clarification in order to not block implementation. Each issue should be written up and addressed in an appropriate epic/issue(s) of its own. This list has been moved from [here](https://github.com/boltlabs-inc/key-mgmt/issues/28).

These are not ordered or dated.

- [ ] Define a specification for the `Delegated` use permission
- [ ] Define concrete policies that an asset owner can specify for a `SelfCustodial` or `Delegated` key
- [ ] Design a recovery flow for all key types.
